Updated the names in Egg Quiz and Word Window
maqsoftware/Pehla-School-Assets pull request #55
Opened 2019-08-26 09:07 UTC by bikashtudu

2019-08-27 06:01 UTC, Shailin commented on localized/games/eggquiz/eggquizliteracy_levels_ur.tsv
> +			120005	sentence_word		We ______ Mubin.			we like mike	like	like^walk ^want
`we like mike` is not changed. Make sure all words are replaced

2019-08-27 06:02 UTC, Shailin commented on localized/games/eggquiz/eggquizliteracy_levels_ur.tsv
> +			170002	sentence_word		____ like Jeesh.			I like josh	I	i^I ^iI
Replace `josh` with `Jeesh`.

2019-08-27 06:02 UTC, Shailin commented on localized/games/eggquiz/eggquizliteracy_levels_ur.tsv
> +			170005	sentence_sentence		صحیح جواب چنیں			सही चयन करे	This is Amreen.	this is ann.^This is Amreen.^this is Amreen.
Replace word `ann` with `Amreen`

2019-08-27 06:05 UTC, Shailin commented on localized/games/eggquiz/eggquizliteracy_levels_ur.tsv
> +			6200005	sentence_word		Fareed is in his _____.			fred is in his bedroom	bedroom	bedroom^kitchen^house
Replace `fred` with `fareed`

2019-08-27 06:06 UTC, Shailin commented on localized/games/eggquiz/eggquizliteracy_levels_ur.tsv
> +			6200010	sentence_word		Chanda is in the _____.			cindy is in the kitchen	kitchen	bedroom^kitchen^house
Please properly review the changes made. The word is not replaced at many places

2019-08-27 06:25 UTC, Shailin commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			73005	word_problem	5 ٹیبل پر 5 سب رکھے ہیں . سام 2 سب کھا لیتا ہے . ٹیبل پر اب کتنے سب بچے ہیں ؟	Five एपल्स टेबल पर हैं। सलमान two एपल्स खाता है। टेबल पर कितने सेब बचे हैं?				3
Urdu text is not updated

2019-08-27 06:25 UTC, Shailin commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			7010	word_problem	صابرہ نے صبح 5 مچھلیاں پکڑی. اس نے دوپہر میں 4 اور مچھلیاں پکڑی. صابرہ نے سب ملکر کتنی مچھلیاں پکڑی؟	स्टैसी ने सुबह 5 मछलियाँ पकड़ीं। उसने दोपहर में 4 और मछलियाँ पकड़ीं। स्टैसी न
Replace word `स्टैसी`

2019-08-27 06:25 UTC, Shailin commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			83004	word_problem	جمیلہ ہے 8 نارنگیاں اور ساجد ہے 4 نارنگیاں. کتنے نارنگیاں کرتے ہیں وہ مکمل طور پر ؟	जेनेट के पास 8 संतरे हैं और शेरोन के पास 4 संतरे हैं। उनके पास कुल मिलाकर कितने संतरे हैं?
Replace word `जेनेट`

2019-08-27 06:25 UTC, Shailin commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			8008	word_problem	ارمان کے پاس ایک ٹوکری میں 11 مانگوس ہے. ارمان اپنی بہن کو 4 مانگوس دیتا ہے. کتنی مانگوس ٹوکری میں رہ رہے ہیں ؟	डिएगो के  एक टोकरी में 11 आम हैं। डिएगो अपनी बहन को 4 आम देता है।
Replace word `डिएगो`

2019-08-27 06:25 UTC, Shailin commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			220008	word_problem	انم كے پاس 7 بسکٹ ہیں . وہ اس میں سے 2 کھا لیتی ہے. اب اسکے پاس کتنے بسکٹ بچے ہیں؟	एना के पास 7 बिस्कुट हैं। वह उनमें से 2 खाती है। उसके पास कितनी बिस्कुट बचे हैं?				5
Properly check Urdu and Hindi text. Either Hindi or Urdu text is not updated at many places

2019-08-27 06:25 UTC, Shailin commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
Replace `सैली` with Urdu name

2019-08-27 13:40 UTC, bikashtudu commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			7012	word_problem	ہاشم كے پاس 4 اسٹیمپس ہیں . اکرم كے پاس ہاشم سے 5 زیادہ ڈال اسٹیمپس ہیں . اکرم كے پاس کتنے ستماپس ہیں ؟	एक पेड़ की शाखा पर 8 पक्षी बैठे हैं। कुछ उड़ गए। अब शाखा पर 3 पक्षी हैं। क
![image](https://user-images.githubusercontent.com/24955098/63776045-381a3200-c8fe-11e9-8e1f-db73867ff403.png)

2019-08-28 06:43 UTC, bikashtudu commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
Urdu spelling and transcript

2019-08-28 07:48 UTC, bikashtudu commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			230002	word_problem	سام نے 7 کوکیز اور جانے نے 2 کوکیز کھائی . سام کی تُلْنا میں جانے نے کتنی کوکیز کم کھائی ؟	सलमान ने 7 बिस्कुट और जाफ़री ने 2 बिस्कुट खाए। सलमान की तुलना में जाफ़री ने कितने कम बि
Urdu transcript

2019-08-28 09:36 UTC, Shailin commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
> +			230001	word_problem	آسمہ کی 9 سال کی عمر ہے. اس کی بہن جوہی ہے 6 سال کی عمر. کتنا بڑی اس کی بہن جوہی کے مقابلے میں آسمہ ہے?	लुसी 9 साल की है। उसकी बहन जूही 6 साल की है। लुसी अपनी बहन जूही से कितनी
Change the word `लुसी`. Check all the files and resolve similar issues

2019-08-28 09:37 UTC, Shailin commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
`सारा` word is not updated

2019-08-28 10:13 UTC, ankitk20 requested changes

2019-08-28 10:13 UTC, ankitk20 commented on localized/games/eggquiz/eggquizmath_levels_ur.tsv
>  MiniTest_7_3	1	73001, 73002, 73003, 73004, 73005
replace two, three, four, etc with 2, 3, 4, etc respectively in TTS speech statements.. Check line 164 and 170

2019-08-28 10:13 UTC, ankitk20 commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
Please fix this issue @bikashtudu

2019-08-28 10:13 UTC, ankitk20 commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
Remove shree

2019-08-28 10:13 UTC, ankitk20 commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
It is muaz i think. Just verify it and update if required.

2019-08-28 11:10 UTC, Shailin requested changes

2019-08-28 11:10 UTC, Shailin commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
Urdu text missing. Add Urdu text from the Excel file

2019-08-28 11:10 UTC, Shailin commented on localized/games/wordwindow/wordwindow_level_ur.tsv
> +en-US	9	2	3	6	"मुन्नी की पेल मे कुछ शख थी। वह 2 और शख पाती है। अब उसके पास कुल 8 शख है। उसके पास पहले से कितने शख थे?"	منّی کی بالٹی میں کچھ سیپیاں تھیں- اسکو 2 اور سیپیاں ملیں- اب اس میں پاس 8 سیپیا
`सैडी` word is not updated

2019-08-28 12:06 UTC, Shailin submitted a review, later dismissed

2019-08-28 14:10 UTC, ankitk20 approved these changes

2019-08-28 14:11 UTC, merged